openapi: 3.0.0
info:
  contact: {}
  description: API for One-Click Swaps
  title: 1Click Swap API
  version: "0.1"
servers:
- url: https://1click.chaindefuser.com
paths:
  /v0/tokens:
    get:
      operationId: getTokens
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TokenResponse'
                type: array
          description: ""
      summary: Returns tokens that can be swapped
      tags:
      - OneClick
  /v0/quote:
    post:
      operationId: getQuote
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Bad Request - Invalid input data
      summary: Returns the best quote with deposit address
      tags:
      - OneClick
  /v0/status:
    get:
      operationId: getExecutionStatus
      parameters:
      - explode: true
        in: query
        name: depositAddress
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetExecutionStatusResponse'
          description: ""
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Deposit address not found
      summary: Returns execution status for a given deposit address
      tags:
      - OneClick
  /v0/deposit/submit:
    post:
      operationId: submitDepositTx
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitDepositTxRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitDepositTxResponse'
          description: ""
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Bad Request - Invalid input data
      summary: Submit a deposit transaction
      tags:
      - OneClick
components:
  schemas:
    TokenResponse:
      example:
        symbol: wNEAR
        blockchain: near
        assetId: nep141:wrap.near
        price: 2.79
        decimals: 24
        priceUpdatedAt: 2025-03-28T12:23:00.07Z
        contractAddress: wrap.near
      properties:
        assetId:
          description: Unique asset identifier
          example: nep141:wrap.near
          type: string
        decimals:
          description: Number of decimals for the token
          example: 24
          type: number
        blockchain:
          description: Blockchain associated with the token
          enum:
          - near
          - eth
          - base
          - arb
          - btc
          - sol
          - ton
          - doge
          - xrp
          - zec
          - gnosis
          - bera
          - bsc
          - pol
          example: near
          type: string
        symbol:
          description: "Token symbol (e.g. BTC, ETH)"
          example: wNEAR
          type: string
        price:
          description: Current price of the token in USD
          example: 2.79
          type: number
        priceUpdatedAt:
          description: Date when the token price was last updated
          example: 2025-03-28T12:23:00.07Z
          format: date-time
          type: string
        contractAddress:
          description: Contract address of the token
          example: wrap.near
          type: string
      required:
      - assetId
      - blockchain
      - decimals
      - price
      - priceUpdatedAt
      - symbol
      type: object
    QuoteRequest:
      example:
        quoteWaitingTimeMs: 3000
        amount: "1000"
        swapType: EXACT_INPUT
        dry: true
        destinationAsset: nep141:sol-5ce3bf3a31af18be40ba30f721101b4341690186.omft.near
        refundType: ORIGIN_CHAIN
        recipientType: DESTINATION_CHAIN
        referral: referral
        recipient: 13QkxhNMrTPxoCkRdYdJ65tFuwXPhL5gLS2Z5Nr6gjRK
        slippageTolerance: 100
        deadline: 2019-08-24T14:15:22Z
        depositType: ORIGIN_CHAIN
        refundTo: 0x2527D02599Ba641c19FEa793cD0F167589a0f10D
        originAsset: nep141:arb-0xaf88d065e77c8cc2239327c5edb3a432268e5831.omft.near
      properties:
        dry:
          description: "\n  Flag indicating whether this is a dry run request.\n\n\
            \  If **true**, the response will **NOT** contain the following fields:\n\
            \  \n   **depositAddress**\n      \n   **timeWhenInactive**\n      \n\
            \   **timeEstimate**\n      \n   **deadline**\n  "
          example: true
          type: boolean
        swapType:
          description: "Whether to use the amount as the output or the input for the\
            \ basis of the swap.\n\n   EXACT_OUTPUT: the **refundTo** address will\
            \ always receive excess tokens back even after the swap is complete.\n\
            \  "
          enum:
          - EXACT_INPUT
          - EXACT_OUTPUT
          type: string
        slippageTolerance:
          description: "Slippage tolerance for the swap. This value is in basis points\
            \ (1/100th of a percent), e.g. 100 for 1% slippage."
          example: 100
          type: number
        originAsset:
          description: ID of origin asset
          example: nep141:arb-0xaf88d065e77c8cc2239327c5edb3a432268e5831.omft.near
          type: string
        depositType:
          description: "Type of deposit address\n  \n  ORIGIN_CHAIN - deposit address\
            \ on origin chain\n  \n  INTENTS - **accountId** inside near intents to\
            \ which you should transfer assets inside intents."
          enum:
          - ORIGIN_CHAIN
          - INTENTS
          type: string
        destinationAsset:
          description: ID of destination asset
          example: nep141:sol-5ce3bf3a31af18be40ba30f721101b4341690186.omft.near
          type: string
        amount:
          description: "Amount to swap as the base amount (can be switched to exact\
            \ input/output using the dedicated flag), denoted in the smallest unit\
            \ of the specified currency (e.g., wei for ETH)"
          example: "1000"
          type: string
        refundTo:
          description: Address for user refund
          example: 0x2527D02599Ba641c19FEa793cD0F167589a0f10D
          type: string
        refundType:
          description: "Type of refund address\n  \n   ORIGIN_CHAIN - assets will\
            \ be refunded to **refundTo** address on origin chain\n   \n   INTENTS\
            \ - assets will be refunded to **refundTo** intents account"
          enum:
          - ORIGIN_CHAIN
          - INTENTS
          type: string
        recipient:
          description: "Recipient address, format should match **recipientType**"
          example: 13QkxhNMrTPxoCkRdYdJ65tFuwXPhL5gLS2Z5Nr6gjRK
          type: string
        recipientType:
          description: "Type of recipient address\n  \n   DESTINATION_CHAIN - assets\
            \ will be transferred to chain of **destinationAsset**\n   \n   INTENTS\
            \ - assets will be transferred to account inside intents"
          enum:
          - DESTINATION_CHAIN
          - INTENTS
          type: string
        deadline:
          description: "Timestamp in ISO format, that identifies when user refund\
            \ will begin if swap was`t completed by then"
          example: 2019-08-24T14:15:22Z
          format: date-time
          type: string
        referral:
          description: Referral identifier
          example: referral
          type: string
        quoteWaitingTimeMs:
          default: 3000
          description: Time in milliseconds user is willing to wait for quote from
            relay
          example: 3000
          type: number
      required:
      - amount
      - deadline
      - depositType
      - destinationAsset
      - dry
      - originAsset
      - recipient
      - recipientType
      - refundTo
      - refundType
      - slippageTolerance
      - swapType
      type: object
    Quote:
      properties:
        depositAddress:
          description: |-
            Deposit address on chain of **originAsset** in case **depositType** is **ORIGIN_CHAIN**.
                  Deposit address inside near intents in case **depositType** is **INTENTS**.
          example: 0x76b4c56085ED136a8744D52bE956396624a730E8
          type: string
        amountIn:
          description: Amount of origin asset
          example: "1000000"
          type: string
        amountInFormatted:
          description: Amount of origin asset in readable format
          example: "1"
          type: string
        amountInUsd:
          description: Amount of origin assets equivalent in USD
          example: "1"
          type: string
        minAmountIn:
          description: Minimum amount of origin asset that will be used for swap
          example: "995000"
          type: string
        amountOut:
          description: Amount of destination asset
          example: "9950000"
          type: string
        amountOutFormatted:
          description: Amount of destination asset in readable format
          example: "9.95"
          type: string
        amountOutUsd:
          description: Amount of destination asset equivalent in USD
          example: "9.95"
          type: string
        minAmountOut:
          description: Minimum amount with slippage taken into account
          example: "9900000"
          type: string
        deadline:
          description: Time when deposit address will become inactive and funds might
            be lost
          example: 2025-03-04T15:00:00Z
          format: date-time
          type: string
        timeWhenInactive:
          description: Time when deposit address will become cold and swap processing
            will take more time
          example: 2025-03-04T15:00:00Z
          format: date-time
          type: string
        timeEstimate:
          description: Estimated time in seconds for swap to be executed after user
            deposit transaction is confirmed
          example: 120
          type: number
      required:
      - amountIn
      - amountInFormatted
      - amountInUsd
      - amountOut
      - amountOutFormatted
      - amountOutUsd
      - minAmountIn
      - minAmountOut
      type: object
    QuoteResponse:
      example:
        quote: ""
        signature: signature
        quoteRequest: ""
        timestamp: 2019-08-24T14:15:22Z
      properties:
        timestamp:
          description: Timestamp in ISO format that took part in deposit address derivation
          example: 2019-08-24T14:15:22Z
          format: date-time
          type: string
        signature:
          description: Signature that means 1click service commit to quote and deposit
            address
          type: string
        quoteRequest:
          allOf:
          - $ref: '#/components/schemas/QuoteRequest'
          description: User request
        quote:
          allOf:
          - $ref: '#/components/schemas/Quote'
          description: Response that contains deposit address for user to send "amount"
            of **originAsset** and possible output amount
      required:
      - quote
      - quoteRequest
      - signature
      - timestamp
      type: object
    BadRequestResponse:
      example:
        message: error message
      properties:
        message:
          example: error message
          type: string
      required:
      - message
      type: object
    TransactionDetails:
      properties:
        hash:
          description: Transaction hash
          example: 0x123abc456def789
          type: string
        explorerUrl:
          description: Explorer URL for the transaction
          type: string
      required:
      - explorerUrl
      - hash
      type: object
    SwapDetails:
      properties:
        intentHashes:
          description: All intent hashes that took part in this swap
          items:
            type: string
          type: array
        nearTxHashes:
          description: All Near transactions executed for this swap
          items:
            type: string
          type: array
        amountIn:
          description: Exact amount of **originToken** after trade was settled
          example: "1000"
          type: string
        amountInFormatted:
          description: Exact amount of **originToken** after trade was settled in
            readable format
          example: "0.1"
          type: string
        amountInUsd:
          description: Exact amount of **originToken** equivalent in USD
          example: "0.1"
          type: string
        amountOut:
          description: Exact amount of **destinationToken** after trade was settled
          example: "9950000"
          type: string
        amountOutFormatted:
          description: Exact amount of **destinationToken** in readable format
          example: "9.95"
          type: string
        amountOutUsd:
          description: Exact amount of **destinationToken** equivalent in USD
          example: "9.95"
          type: string
        slippage:
          description: Actual slippage
          example: 50
          type: number
        originChainTxHashes:
          description: Hashes and explorer URLs for all transactions on origin chain
          items:
            $ref: '#/components/schemas/TransactionDetails'
          type: array
        destinationChainTxHashes:
          description: Hashes and explorer URLs for all transactions on destination
            chain
          items:
            $ref: '#/components/schemas/TransactionDetails'
          type: array
        refundedAmount:
          description: Amount of **originAsset** that got transferred to **refundTo**
          example: "1000"
          type: string
        refundedAmountFormatted:
          description: Refunded amount in readable format
          example: "0.1"
          type: string
        refundedAmountUsd:
          description: Refunded amount equivalent in USD
          example: "0.1"
          type: string
      required:
      - destinationChainTxHashes
      - intentHashes
      - nearTxHashes
      - originChainTxHashes
      type: object
    GetExecutionStatusResponse:
      example:
        quoteResponse: ""
        swapDetails: ""
        status: KNOWN_DEPOSIT_TX
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        quoteResponse:
          allOf:
          - $ref: '#/components/schemas/QuoteResponse'
          description: Quote response from original request
        status:
          enum:
          - KNOWN_DEPOSIT_TX
          - PENDING_DEPOSIT
          - INCOMPLETE_DEPOSIT
          - PROCESSING
          - SUCCESS
          - REFUNDED
          - FAILED
          type: string
        updatedAt:
          description: Last time the state was updated
          format: date-time
          type: string
        swapDetails:
          allOf:
          - $ref: '#/components/schemas/SwapDetails'
          description: Details of actual swaps and withdrawals
      required:
      - quoteResponse
      - status
      - swapDetails
      - updatedAt
      type: object
    SubmitDepositTxRequest:
      example:
        depositAddress: 0x2527D02599Ba641c19FEa793cD0F167589a0f10D
        txHash: 0x123abc456def789
      properties:
        txHash:
          description: Transaction hash of your deposit
          example: 0x123abc456def789
          type: string
        depositAddress:
          description: Deposit address for the quote
          example: 0x2527D02599Ba641c19FEa793cD0F167589a0f10D
          type: string
      required:
      - depositAddress
      - txHash
      type: object
    SubmitDepositTxResponse:
      example:
        quoteResponse: ""
        swapDetails: ""
        status: KNOWN_DEPOSIT_TX
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        quoteResponse:
          allOf:
          - $ref: '#/components/schemas/QuoteResponse'
          description: Quote response from original request
        status:
          enum:
          - KNOWN_DEPOSIT_TX
          - PENDING_DEPOSIT
          - INCOMPLETE_DEPOSIT
          - PROCESSING
          - SUCCESS
          - REFUNDED
          - FAILED
          type: string
        updatedAt:
          description: Last time the state was updated
          format: date-time
          type: string
        swapDetails:
          allOf:
          - $ref: '#/components/schemas/SwapDetails'
          description: Details of actual swaps and withdrawals
      required:
      - quoteResponse
      - status
      - swapDetails
      - updatedAt
      type: object
